name: 자동 통합 CI

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install  

    - name: Merge pull requests
      run: |
        TODAY=$(TZ='Asia/Seoul' date +%Y%m%d)

        PRS=$(gh pr list --state open --base main --json number,title --jq '.[] | select(.title | startswith("[" + "'"$TODAY"'" + "]")) | .number')
        for pr in $PRS; do
          echo "Merging PR #$pr"
          gh pr merge $pr --merge --admin
        done
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
